In [5]:
import numpy
import torch
import mobster as mb

import numpy as np

%load_ext autoreload
%autoreload 2
%aimport mobster

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
data = mb.load_example_data("./")
data.keys()

dict_keys(['1:0', '1:1', '2:0', '2:1', '2:2'])

In [7]:
import pyro

pyro.enable_validation(True)
fitted = mb.fit_mobster(data,0,1, subclonal_prior="Moyal", multi_tail = False,
                        purity = 0.99,  truncated_pareto=True, max_it = 500,
                        lr = 0.01,  e = 1e-10, lrd_gamma = 0.01,k_means_init = True,
        number_of_trials_subclonal= 500, prior_lims_k=[0.1,100000.],alpha_precision_concentration = 2,
                        alpha_precision_rate = 0.01,
                        prior_lims_clonal=[0.1,100000.],
                        number_of_trials_clonal_mean= 300, CUDA = False)


Running MOBSTER on 5 karyotypes with 0 subclones.
Fitting a model with tail


ELBO: 800.964904672  : 100%|██████████| 500/500 [00:26<00:00, 18.99it/s]

Computing cluster assignements.
tensor([0.9802])
tensor([0.2475])
tensor([0.2475, 0.4950])
tensor([0.1104, 0.2207])
tensor([0.0622, 0.1244])
Computing information criteria.
Done!



In [4]:



mb.plot_results(data, fitted, output= "cane.png", drivers=None)

In [9]:
import pyro.distributions as dist
torch.autograd.set_detect_anomaly(True)
alpha = torch.tensor(1., requires_grad = True)
pp = mb.ParetoBinomial.ParetoBinomial(alpha,0.25,0.06,data["2:2"][:,1] ).log_prob(data["2:2"][:,0])
#pp

In [15]:
mb.theo_clonal_num("1:1") / mb.theo_clonal_tot("1:1")

tensor([0.5000])

In [22]:
import pyro.distributions as dist

dist.LogNormal(0,0.1).mean

tensor(1.0050)

In [5]:
torch.trapz(mb.ParetoBinomial.ParetoBinomial(torch.tensor(1),0.25,0.06,torch.tensor(50) ).log_prob(torch.arange(0,51)).exp(), torch.arange(0,51))
#pp

tensor(0.9941)

In [5]:
mb.ParetoBinomial.ParetoBinomial(torch.tensor(1),0.25,0.06,torch.tensor(50) ).log_prob(torch.arange(0,51))

tensor([[0.0600],
        [0.0616],
        [0.0632],
        [0.0648],
        [0.0664],
        [0.0680],
        [0.0696],
        [0.0712],
        [0.0728],
        [0.0744],
        [0.0760],
        [0.0776],
        [0.0792],
        [0.0808],
        [0.0824],
        [0.0839],
        [0.0855],
        [0.0871],
        [0.0887],
        [0.0903],
        [0.0919],
        [0.0935],
        [0.0951],
        [0.0967],
        [0.0983],
        [0.0999],
        [0.1015],
        [0.1031],
        [0.1047],
        [0.1063],
        [0.1079],
        [0.1095],
        [0.1111],
        [0.1127],
        [0.1143],
        [0.1159],
        [0.1175],
        [0.1191],
        [0.1207],
        [0.1223],
        [0.1239],
        [0.1255],
        [0.1271],
        [0.1287],
        [0.1303],
        [0.1318],
        [0.1334],
        [0.1350],
        [0.1366],
        [0.1382],
        [0.1398],
        [0.1414],
        [0.1430],
        [0.1446],
        [0.1462],
        [0

tensor([  0.3661,   1.7340,   2.4277,   2.7464,   2.8234,   2.7417,   2.5624,
          2.3307,   2.0763,   1.8126,   1.5393,   1.2484,   0.9288,   0.5701,
          0.1634,  -0.2979,  -0.8189,  -1.4030,  -2.0527,  -2.7698,  -3.5555,
         -4.4108,  -5.3363,  -6.3328,  -7.4008,  -8.5410,  -9.7540, -11.0406,
        -12.4018, -13.8387, -15.3526, -16.9449, -18.6174, -20.3722, -22.2117,
        -24.1387, -26.1564, -28.2687, -30.4801, -32.7960, -35.2228, -37.7682,
        -40.4419, -43.2557, -46.2249, -49.3697, -52.7179, -56.3097, -60.2095,
        -64.5345, -69.5721])

In [14]:
kk = torch.ones(120,51)

In [28]:
torch.cat([kk[0:-1].unsqueeze(-1),kk[1:].unsqueeze(-1)],2).shape

torch.Size([119, 51, 2])

In [ ]:
logsumexp()